#!/bin/bash

LOCUST_MODE=${LOCUST_MODE:="standalone"}
LOCUST_MASTER=${LOCUST_MASTER:=""}
LOCUST_LOCUSTFILE_PATH=${LOCUST_LOCUSTFILE_PATH:="/locust-tasks/locustfile.py"}
LOCUST_LOCUSTFILE_URL=${LOCUST_LOCUSTFILE_URL:=""}
LOCUST_TARGET_HOST=${LOCUST_TARGET_HOST:="https://example.com"}
LOCUST_NO_WEB=${LOCUST_NO_WEB:=""}
LOCUST_USERS_SPAWN=${LOCUST_USERS_SPAWN:="10"}
LOCUST_HATCH_RATE=${LOCUST_HATCH_RATE:="1"}
LOCUST_RUN_TIME=${LOCUST_RUN_TIME:="1m"}

if [ ! -z "$LOCUST_LOCUSTFILE_URL" ]; then
    LOCUST_LOCUSTFILE_PATH="/locust-tasks/locustfile.py"
    curl $LOCUST_LOCUSTFILE_URL -o $LOCUST_LOCUSTFILE_PATH
fi

LOCUST_PATH="/usr/local/bin/locust"

if [ ! -z "$LOCUST_NO_WEB" ]; then
    LOCUST_FLAGS="-f $LOCUST_LOCUSTFILE_PATH --host=$LOCUST_TARGET_HOST --no-web -c $LOCUST_USERS_SPAWN -r $LOCUST_HATCH_RATE --run-time $LOCUST_RUN_TIME"
else 
    LOCUST_FLAGS="-f $LOCUST_LOCUSTFILE_PATH --host=$LOCUST_TARGET_HOST"
fi

echo $LOCUST_FLAGS
exec $LOCUST_PATH $LOCUST_FLAGS
